#!/bin/bash

#PBS -q normal
#PBS -l select=1:ngpus=1:mem=512gb
#PBS -l walltime=05:30:00

echo "Start the script"
echo "PBS_O_WORKDIR: $PBS_O_WORKDIR"

module restore -f vllm
module list
source /home/users/ntu/n2402836/scratch/venv_adaspec/bin/activate
echo "Virtual env: $VIRTUAL_ENV"

cd /home/users/ntu/n2402836/scratch/AdaSpec/scripts_e2e
bash /home/users/ntu/n2402836/scratch/AdaSpec/scripts_e2e/3_run_smartspec_dynamic.sh
